### PR TITLE
fix: added overload method for transaction.createQuery to handle namespace issue

### LINKED ISSUE #484: transaction.createQuery with hasAncestor and filter require namespace (throw exception when namespace is missing)
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-datastore/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: OpenSuSE 15.1
  - Node.js version: v10.16.0
  - npm version: 6.9.0
  - `@google-cloud/datastore` version: 4.2.0

#### Steps to reproduce
1. Run this function
```javascript
'use strict';


const { Datastore } = require('@google-cloud/datastore');


const datastore = new Datastore();


const kind = 'ImmutableEntity';

function getData(description, version) {
  return {
    description,
    createdAt: new Date(),
    isLatest: true,
    version
  };
}

async function seed() {
  const key1 = datastore.key(kind);
  const entity1 = {
    key: key1,
    data: getData('Root item 1', 0)
  };

  const key2 = datastore.key(kind);
  const entity2 = {
    key: key2,
    data: getData('Root item 2', 0)
  };

  try {
    await datastore.save([entity1, entity2]);
  } catch (err) {
    console.log('Seed error...');
    console.log(err);
  }

  return [key1, key2];
}

function delay(ms) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, ms);
  });
}

// Update method 1
async function update1(key, description, ms) {
  console.log(`Starting update... | ${key.id} # ${description}`);
  const updateKey = datastore.key([kind, datastore.int(key.id), kind]);
  const transaction = datastore.transaction();

  try {
    await transaction.run();
    console.log(`Starting transaction | ${key.id} # ${description}`);
    const [root] = await transaction.get(key);
    const query = datastore.createQuery(kind).hasAncestor(key).filter('isLatest', true);
    const [results] = await transaction.runQuery(query);
    if (results.length !== 1) {
      await transaction.rollback();
      console.log(`Conflict | ${key.id} # ${description}`);
      return;
    }

    root.version += 1;

    const rootEntity = {
      key,
      data: root
    };

    const entities = [rootEntity];

    const data = results[0];
    const latestKey = data[datastore.KEY];
    if (latestKey.path.length > 2) {
      data.updatedAt = new Date();
      data.isLatest = false;
      const entity = {
        key: latestKey,
        data
      };

      entities.push(entity);
    } else {
      root.isLatest = false;
    }

    const updateEntity = {
      key: updateKey,
      data: getData(description, root.version)
    };

    entities.push(updateEntity);

    if (ms) {
      console.log(`Await: ${ms} ms`);
      await delay(ms);
      console.log('Save...');
    }

    transaction.save(entities);
    await transaction.commit();
    console.log(`Commit | ${key.id} # ${description}`);
  } catch (err) {
    await transaction.rollback();
    console.log('Update error!!!');
    console.log('Key:');
    console.log(key);
    console.log(`Description: ${description}`);
    console.log('Error:');
    console.log(err);
    console.log(`Rollback on error | ${key.id} # ${description}`);
  }
}

// Update method 2
async function update2(key, description, ms) {
  console.log(`Starting update... | ${key.id} # ${description}`);
  const updateKey = datastore.key([kind, datastore.int(key.id), kind]);
  const transaction = datastore.transaction();

  try {
    await transaction.run();
    console.log(`Starting transaction | ${key.id} # ${description}`);
    const query = transaction.createQuery(kind).hasAncestor(key).filter('isLatest', true);
    const [results] = await transaction.runQuery(query);
    if (results.length !== 1) {
      await transaction.rollback();
      console.log(`Conflict | ${key.id} # ${description}`);
      return;
    }

    const entities = [];

    const data = results[0];
    const latestKey = data[datastore.KEY];
    data.updatedAt = new Date();
    data.isLatest = false;
    const entity = {
      key: latestKey,
      data
    };

    entities.push(entity);

    const updateEntity = {
      key: updateKey,
      data: getData(description, new Date())
    };

    updateEntity.data.parent = key;
    updateEntity.data.parentId = datastore.int(key.id);

    entities.push(updateEntity);

    if (ms) {
      console.log(`Await: ${ms} ms`);
      await delay(ms);
      console.log('Save...');
    }

    transaction.save(entities);
    await transaction.commit();
    console.log(`Commit | ${key.id} # ${description}`);
  } catch (err) {
    await transaction.rollback();
    console.log('Update error!!!');
    console.log('Key:');
    console.log(key);
    console.log(`Description: ${description}`);
    console.log('Error:');
    console.log(err);
    console.log(`Rollback on error | ${key.id} # ${description}`);
  }
}

async function update(key, description, ms) {
  return update2(key, description, ms);
}

async function test() {
  console.log('Seeding...');
  const keys = await seed();

  await delay(1500);
  console.log('Running test case...');
  // Create first update
  await update(keys[0], 'Root item 1 -> version 2');

  await delay(5000);
  update(keys[0], 'Root item 1 -> version 3', 1500);
  await delay(100);
  await delay(1000);
  await update(keys[0], 'Root item 1 -> version 4', 100);
  await delay(2000);

  // Check conflict
  update(keys[0], 'Root item 1 -> version 5', 10000);
  await delay(2000);
  await update(keys[0], 'Root item 1 -> version 6', 100);
  console.log('Done');

  //
  await delay(10000);
  const query = datastore.createQuery(kind).hasAncestor(keys[0]);
  const [logs] = await datastore.runQuery(query);
  console.log('All:');
  console.log(logs);
  console.log('Latest');
  const queryLatest = datastore.createQuery(kind).hasAncestor(keys[0]).filter('isLatest', true);
  const [latestEntities] = await datastore.runQuery(queryLatest);
  console.log(latestEntities);

  console.log('KEY');
  const key = keys[0];
  console.log(`typeof key: ${typeof key}`);
  console.log(`typeof key.name: ${typeof key.name}`);
  console.log(`typeof key.id: ${typeof key.id}`);
  console.log(`typeof key.path: ${typeof key.path}`);
  console.log(`typeof key.path[0]: ${typeof key.path[0]}`);
  console.log(`typeof key.path[1]: ${typeof key.path[1]}`);
  const rebuildKey = datastore.key([kind, key.id]);
  const rebuildKeyFromPath = datastore.key([kind, key.path[1]]);
  const rebuild = datastore.key([kind, datastore.int(key.id)]);
  console.log(rebuild);
  console.log(rebuildKey);
  console.log(rebuildKeyFromPath);
  console.log(`typeof datastore.int(key.id) ${datastore.int(key.id)}`);
}

test().then(() => {
  console.log('DONE');
}).catch((err) => {
  console.log('ERROR:');
  console.log(err);
});

```
2. We receive unexpected exception.
Exception:
`
{ Error: The query namespace is 'ImmutableEntity' but ancestor namespace is ''.
    at Http2CallStream.call.on (/home/mushu/Projects/jaci-vn/ecommerce/api/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/home/mushu/Projects/jaci-vn/ecommerce/api/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 3,
  details:
   'The query namespace is \'ImmutableEntity\' but ancestor namespace is \'\'.',
  metadata: Metadata { options: undefined, internalRepr: Map {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
`
3. If we replace:
`
const query = transaction.createQuery(kind).hasAncestor(key).filter('isLatest', true);
`
to
`
const query = datastore.createQuery(kind).hasAncestor(key).filter('isLatest', true);
`
Then it work well.

This is different from document: https://googleapis.dev/nodejs/datastore/latest/Transaction.html#createQuery

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by laljikanjareeya**
Fixes #484 

respective function  `transaction.createQuery` is strictly expecting `namespace` first and than `kind` parameter, to call without `namespace` parameter created overload method which is expecting only `kind` parameter.

### CODE REVIEW

File: src/transaction.ts [hunk 1]
```diff
@@ -300,7 +327,15 @@ class Transaction extends DatastoreRequest {
...
    */
-  createQuery(namespace: string, kind?: string | string[]): Query {
+  createQuery(
+    namespaceOrKind?: string | string[],
+    kind?: string | string[]
+  ): Query {
+    let namespace = namespaceOrKind as string;
+    if (arguments.length < 2) {
+      kind = namespaceOrKind;
+      namespace = this.namespace!;
```
Comment (callmehiphop) [inline src/transaction.ts]: How does this fix #486 exactly?

`this.namespace` is just an [alias to `this.datastore.namespace](https://github.com/googleapis/nodejs-datastore/blob/master/src/transaction.ts#L75)` and the [`datastore.createQuery`](https://github.com/googleapis/nodejs-datastore/blob/master/src/index.ts#L647) method contains the same logic here.

Comment (laljikanjareeya) [reply src/transaction.ts]: @callmehiphop  fair question,
while passing only kind in `transaction.createQuery` it internally calls `datastore.createQuery` with two arguments namespace(that user pass as kind) and kind as `undefined`.
in above scenario `datastore.createQuery` argument condition will not fulfill(as it got two arguments) so it will take first argument as namespace and second as kind that is not correct. 

it is necessary to check argument condition in `transaction.createQuery` as well.

Comment (callmehiphop) [reply src/transaction.ts]: Oh, so would you say that the check in `datastore.createQuery` is bad? And instead of checking for the number of arguments, we should be checking if the second argument is not undefined?

Comment (laljikanjareeya) [reply src/transaction.ts]: true @callmehiphop, made changes in `datastore.createQuery` condition as per your suggestion. keeping overload for `transaction.createQuery` now.

File: src/transaction.ts [hunk 2]
```diff
@@ -284,8 +288,31 @@ class Transaction extends DatastoreRequest {
...
+   *
+   *     transaction.commit((err) => {
+   *       if (!err) {
+   *         // Transaction committed successfully.
+   *       }
+   *     });
+   *   });
+   * });
+   *
+   * //Run the query inside the transaction.with namespace
```
Comment (callmehiphop) [inline src/transaction.ts]: Probably want a space inserted between the comment characters and the comment itself.

File: src/transaction.ts [hunk 3]
```diff
@@ -284,8 +288,31 @@ class Transaction extends DatastoreRequest {
    *   if (err) {
    *     // Error handling omitted.
    *   }
+   *   const ancestorKey = datastore.key(['ParentCompany', 'Alphabet']);
    *
-   *   const query = transaction.createQuery('Company');
+   *   const query = transaction.createQuery('Company').hasAncestor(ancestorKey);
```
Comment (callmehiphop) [inline src/transaction.ts]: Is this longer than 80 characters? If so can we format it?

File: src/transaction.ts [hunk 4]
```diff
@@ -284,8 +288,31 @@ class Transaction extends DatastoreRequest {
...
+   * });
+   *
+   * //Run the query inside the transaction.with namespace
+   * transaction.run((err) => {
+   *   if (err) {
+   *     // Error handling omitted.
+   *   }
+   *   const ancestorKey = datastore.key(['ParentCompany', 'Alphabet']);
+   *
+   *   const query = transaction.createQuery('CompanyNamespace','Company').hasAncestor(ancestorKey);
```
Comment (callmehiphop) [inline src/transaction.ts]: Is this longer than 80 characters? If so can we format it?
