### PR TITLE
fix: Resolve getProjectId

### LINKED ISSUE #844: getProjectId never resolves
#### Environment details

  - OS: Ubuntu 20.04.2 LTS 
  - Node.js version: v14.17.0
  - npm version: 6.14.13
  - `@google-cloud/datastore` version: 6.4.1

#### Steps to reproduce

Run the following code:
```js
const { Datastore } = require('@google-cloud/datastore');

const datastore = new Datastore();
datastore.getProjectId()
  .then(projectId => console.log(`projectId: ${projectId}`))
  .catch(err => console.log(`err ${err}`));
```

Expected output is `projectId: <my-project-id>` or `err <error>` but no output is shown.

### Workaround

I had a quick look and it seems like `getProjectId` is promisified even though it already returns a promise. I added `getProjectId` to the promisify exclude list in `/node_modules/@google-cloud/datastore/build/src/index.js:1484`:
```js
promisify_1.promisifyAll(Datastore, {
    exclude: [
        'double',
        'isDouble',
        'geoPoint',
        'isGeoPoint',
        'index',
        'int',
        'isInt',
        'createQuery',
        'key',
        'isKey',
        'keyFromLegacyUrlsafe',
        'transaction',
        'getProjectId'
    ],
});
```
Also found at: https://github.com/googleapis/nodejs-datastore/blob/ccc466a5fce8cb78a0980f961bfa473c56a12c38/src/index.ts#L1747-L1762

With `getProjectId` excluded, the output is `projectId: <my-project-id>` which is the expected output.

### PR DESCRIPTION
**Pull request by billyjacobson**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-datastore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #844 🦕

### CODE REVIEW

**Comment by billyjacobson** [comment]
Hey I'm not sure how to test this but was just doing a solution based on the GitHub issue

File: src/index.ts [hunk 1]
```diff
@@ -1749,6 +1749,7 @@ promisifyAll(Datastore, {
     'double',
     'isDouble',
     'geoPoint',
+    'getProjectId',
```
Comment (JustinBeckwith) [inline src/index.ts:1752]: It looks like this makes an actual change to the source of the library - can you use the `fix:` conventional commit prefix to make sure this triggers a launch?

File: system-test/datastore.ts [hunk 2]
```diff
@@ -60,6 +60,11 @@ describe('Datastore', () => {
     assert.ok(keys);
   });
 
+  it('should get the project id', async () => {
+    const projectId = await datastore.getProjectId();
+    assert.notEqual(projectId, null);
```
Comment (JustinBeckwith) [inline system-test/datastore.ts:65]: It could still come back as `undefined` here, or an empty string :/  What do you think of `assert.ok(projectId)` to capture falsey values?

**Review by JustinBeckwith — APPROVED** [review]
LGTM w/nits

File: system-test/datastore.ts (hunk 2 above)
Comment (billyjacobson) [reply system-test/datastore.ts:65]: I'm fine with that. I'd just assume that for the other tests to pass the projectid would need to be defined

**Comment by crwilcox** [comment]
The cause of the test failure was that it seems import/export uses a testing project that didn't have legacy reader access to the bucket we use. This is likely related to an issue that happened ~2 weeks back where the test bucket was erroneously deleted. When recreated, perms for this extra account, `billy-testing`, were not granted.
